### ISSUE TITLE
Keeps asking for pass

### ISSUE THREAD

**Issue by sweebee** [alanreid/bravia#7]
Every time i run the demo it keeps asking for a password. I already tried to empty cookies.json, but that didn't help.

**Comment by alanreid** [comment]
I heard others had the same issue as well (#4 and #5), but although there seems to be a workaround, it's not an actual solution. 

Since I moved, I unfortunately no longer have a Bravia TV. I tried my best to assist so far, but I can't reproduce the issues myself, so it's quite hard to get anything done. 

If you find a fix, I'd gladly appreciate if you could send a PR or let me know what it was.

Thanks and sorry for the hassle

**Comment by alanreid** [comment]
Hi there,

I got a Bravia TV for a week again and I was able to reproduce and fix the issue. 
The problem was with the tough-cookie package (`tough-cookie/lib/cookie.js:576`), which replaces the tailing slash only on lookup and not on save. This means it's not able to find a cookie that's saved as `/sony/`, because it will always look it up as `/sony`. 

So pull the latest changes and it should work again.

Hope it helps!
Alan
